apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relationship-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: change-intelligence-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-worker
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbox-relay
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: d39b6820-67e3-4c9a-bd15-ca63c65fa90c
automountServiceAccountToken: true
