apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relationship-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: change-intelligence-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-worker
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbox-relay
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 7a0d7710-a801-403c-96d0-c08e7e259f25
automountServiceAccountToken: true
